# Name of output folder
sample_name: sample_1

# Input FASTQ files. Can be a (zipped) FASTQ file or a folder containing (zipped) FASTQ files
# Input file should be basecalled with guppy 3.6 or higher and trimmed using porechop!
input_fastq: trimmed.fastq

# Reference genome
reference_fasta: "GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"

# BED file containing intervals with regions that are going to be analysed
# Optimally one interval per targeted gene but can also be a single interval
# covering all targeted genes.
targets_bed: hg38_chr6.bed


############################
######### Optional #########
############################
#
# Max differences between UMI in read and UMI pattern
umi_errors: 3

# Min number of reads required for a consensus read
min_reads_per_cluster: 1

# Max number of 1D used for a consensus read
max_reads_per_cluster: 60

# Medaka model used to compute consensus reads
medaka_model: "r941_min_high_g360"



