channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.6
  - snakemake-minimal
  - vsearch
  - minimap2
  - samtools
  - tabix
  - porechop
  - pip
  - pip:
    - catfishq
    - medaka==1.1.3
